const names = [
    'Tony Soprano',
    'Jennifer Melfi',
    'Carmela Soprano',
    'Christopher Moltisanti',
    'Junior Soprano',
    'Big Pussy Bonpensiero',
    'Silvio Dante',
    'AJ Soprano',
    'Meadow Soprano',
    'Paulie Gualtieri',
    'Livia Soprano',
    'Adriana La Cerva',
    'Richie Aprile',
    'Janice Soprano',
    'Artie Bucco',
    'Charmaine Bucco',
    'Ralphie Cifaretto',
    'Furio Giunta',
    'Bobby Baccalleri',
    'Johnny Sack',
    'Vito Spatafore',
    'Tony Blundetto',
    'Johnny Cakes',
    'Rosalie Aprile',
    'Patsy Parisi',
    'Angie Bonpensiero',
    'Little Paulie',
    'Carmine Lupertazzi',
    'Little Carmine Lupertazzi',
    'Phil Leotardo',
    'Hesh Rabkin',
    'Father Intintola',
    'Mikey Palmice',
    'Jackie Aprile Jr',
    'Ginny Sacrimoni',
    'Finn DeTrolio',
    'Jackie Aprile',
    'Beansie',
    'Cosette',
    'Pie o Mie',
    'The ducks'
];

const locations = [
    'Carmelas spec house',
    'Satriales',
    'Vesuvio',
    'The Bada Bing',
    'The Pine Barrens',
    'Stugots',
    'Crazy Horse'
]

const phrases = [
    'Oh',
    'Gabagoul',
    'Cause theyre stupid thats why',
    'I know seniors who are inspired',
    'Che bruta',
    'Goomar',
    'RICO',
    'Made man',
    'I wish the lord would take me now'
]