const names = [
    'TONY SOPRANO',
    'JENNIFER MELFI',
    'CARMELA SOPRANO',
    'CHRISTOPHER MOLTISANTI',
    'JUNIOR SOPRANO',
    'BIG PUSSY BONPENSIERO',
    'SIVIO DANTE',
    'AJ SOPRANO',
    'MEADOW SOPRANO',
    'PAUIE GUATIERI',
    'LIVIA SOPRANO',
    'ADRIANA LA CERVA',
    'RICHIE APRILE',
    'JANICE SOPRANO',
    'ARTIE BUCCO',
    'CHARMAINE BUCCO',
    'RALPHIE CIFARETTO',
    'FURIO GIUNTA',
    'BOBBY BACCAERI',
    'JOHNNY SACK',
    'VITO SPATAFORE',
    'TONY BLUNDETTO',
    'JOHNNY CAKES',
    'ROSALIE APRILE',
    'PATSY PARISI',
    'ANGIE BONPENSIERO',
    'LITTLE PAULIE',
    'CARMINE LUPERTAZZI',
    'LITTLE CARMINE LUPERTAZZI',
    'PHI LEOTARDO',
    'HESH RABKIN',
    'FATHER INTINTOLA',
    'MIKEY PALMICE',
    'JACKIE APRILE JR',
    'GINNY SACRIMONI',
    'FINN DETROLIO',
    'JACKIE APRILE',
    'BEANSIE',
    'COSETTE',
    'PIE O MIE',
    'THE DUCKS'
];


// const locations = [
//     'Carmelas spec house',
//     'Satriales',
//     'Vesuvio',
//     'The Bada Bing',
//     'The Pine Barrens',
//     'Stugots',
//     'Crazy Horse'
// ]

// const phrases = [
//     'Oh',
//     'Gabagoul',
//     'Cause theyre stupid thats why',
//     'I know seniors who are inspired',
//     'Che bruta',
//     'Goomar',
//     'RICO',
//     'Made man',
//     'I wish the lord would take me now'
// ]